group:
  - files:
      - .github/FUNDING.yml
      - LICENSE
    repos: |
      nextauthjs/next-auth-example
      nextauthjs/next-auth-gatsby-example

nextauthjs/next-auth-example:
  - source: apps/example-nextjs
    dest: .
    deleteOrphaned: true

nextauthjs/next-auth-gatsby-example:
  - source: apps/example-gatsby
    dest: .
    deleteOrphaned: true
