name: Question
description: Ask a question about NextAuth.js or for help using it
title: "[Question]: "
labels: question

body:
  - type: markdown
    attributes:
      value: |
        We are glad that you have a question about this library. Please fill out the following information:
  - type: textarea
    id: question
    attributes:
      label: Question 💬
      description: Please provide an in-depth description of the question you have.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Make sure you [link]() to external documentation if necessary and provide inline code examples like so:

        ```js
        function myAwesomeNextAuthFeature() {
          return 💚
        }
        ```

        **NOTE:** Questions will be converted to Discussions. You can find them [here](https://github.com/nextauthjs/next-auth/discussions)!    

  - type: input
    id: codesandbox
    attributes: 
      label: How to reproduce ☕️ 
      description: Please provide a link to a minimal reproduction that represents your question
    validations:
      required: true 
  - type: markdown
    attributes:
      value: |
        We encourage you to use the template set-up on **CodeSandbox** as a playground to represent your question or doubt:
        - [`next-auth-example`](https://codesandbox.io/s/next-auth-example-1kktb)
  - type: markdown
    attributes:
      value: "## Contributing 🙌🏽"
  - type: markdown
    attributes: 
      value: |
        It takes a lot of work 🏋🏻‍♀️ maintaining a library like `next-auth`; any contribution is more than welcome 💚
        In case you're willing to help answer this question, please let us know here, and we'll reach you 😊 . Otherwise, you can have a look at the issues labelled with [`"good first issue"`](https://github.com/nextauthjs/next-auth/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) and pick any of them.      
  
