name: Release Flow

on:
  push:
    branches:
      - "main"
      - "beta"
      - "next"
      - "3.x"
  pull_request:

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Init
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Dependencies
        uses: bahmutov/npm-install@v1
      - name: Run tests
        run: npm test -- --collectCoverage
      - name: Coverage
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage1.xml,./coverage2.xml # optional
          fail_ci_if_error: false
          verbose: true # optional (default = false)
      - name: Build
        run: npm run build
  release:
    name: Release
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Init
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Dependencies
        uses: bahmutov/npm-install@v1
      - name: Release
        run: npx semantic-release@17
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
