name: Release

on:
  push:
    branches:
      - "main"
      - "beta"
      - "next"
      - "3.x"
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Init
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Dependencies
        uses: bahmutov/npm-install@v1
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm run test -- -- --coverage --verbose
        env:
          UPSTASH_REDIS_URL: ${{ secrets.UPSTASH_REDIS_URL }}
          UPSTASH_REDIS_KEY: ${{ secrets.UPSTASH_REDIS_KEY }}
      - name: Coverage
        uses: codecov/codecov-action@v1
        with:
          directory: ./coverage
          fail_ci_if_error: false
  release-branch:
    name: Publish branch
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.event_name == 'push' }}
    environment: Production
    steps:
      - name: Init
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Dependencies
        uses: bahmutov/npm-install@v1
      - name: Publish to npm and GitHub
        run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # We save default token elsewhere so we can safely swap later on
          # None of the current maintainers have access to the original token to change
          # or get a new one from npm.
          # When all packages have been migrated to `@next-auth`, we can have a single token
          # because we have access to that npm account.
          NPM_TOKEN_PKG: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN_ORG: ${{ secrets.NPM_TOKEN_ORG }}
          DRY_RUN: true
  release-pr:
    name: Publish PR
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.event_name == 'pull_request' }}
    environment: Preview
    steps:
      - name: Init
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Dependencies
        uses: bahmutov/npm-install@v1
      - name: Determine version
        uses: ./.github/version-pr
        id: determine-version
        env:
          PR_NUMBER: ${{ github.event.number }}
      - name: Publish to npm
        run: |
          cd packages/next-auth
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm publish --access public --tag experimental
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Comment version on PR
        uses: NejcZdovc/comment-pr@v1
        with:
          message: "🎉 Experimental release [published on npm](https://www.npmjs.com/package/next-auth/v/${{ env.VERSION }})!\n\n```sh\nnpm i next-auth@${{ env.VERSION }}\n```\n```sh\nyarn add next-auth@${{ env.VERSION }}\n```"
        env:
          VERSION: ${{ steps.determine-version.outputs.version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
